version: "3.9"

services:
  api:
    build:
      context: ./
      dockerfile: ./compose/local/api/Dockerfile
    hostname: api
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/home/app
