name: Build

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create empty .env
        run: |
          touch .env
      - name: Lint
        run: ./scripts/lint



